const ERROR_TYPE = {
  ERROR_UNIQUE_SLUG: 'ERROR_UNIQUE_SLUG',
  ERROR_UNIQUE_CATEGORY: 'ERROR_UNIQUE_CATEGORY',
  ERROR_SERVICE_USING_CATEGORY: 'ERROR_SERVICE_USING_CATEGORY',
  ERROR_SERVICE_WORKING_TIME_USING_CURRENT: 'ERROR_SERVICE_WORKING_TIME_USING_CURRENT'
}

export {
  ERROR_TYPE
}
